apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-ingestion-agent
  namespace: signal-detection
  labels:
    app.kubernetes.io/name: content-ingestion-agent
    app.kubernetes.io/component: ingestion
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: content-ingestion-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: content-ingestion-agent
        app.kubernetes.io/component: ingestion
    spec:
      containers:
      - name: content-ingestion
        image: ghcr.io/simardeep1792/signal-detection-ingestion:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8090
          name: agent-api
        env:
        - name: AGENT_TYPE
          value: "content-ingestion"
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: signal-detection-config
              key: database_url
        - name: BATCH_SIZE
          valueFrom:
            configMapKeyRef:
              name: signal-detection-config
              key: batch_size
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: signal-detection-config
              key: log_level
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: data-storage
          mountPath: /data
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: signal-detection-data
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: content-ingestion-agent
  namespace: signal-detection
spec:
  selector:
    app.kubernetes.io/name: content-ingestion-agent
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: agent-api
    port: 8090
    targetPort: 8090
---
apiVersion: openagent.dev/v1
kind: Agent
metadata:
  name: content-ingestion-agent
  namespace: signal-detection
spec:
  type: content-ingestion
  version: "1.0.0"
  capabilities:
    - name: "ingest.json-documents"
      description: "Process JSON document collections (replaces Foresight m1 extract)"
      input_schema:
        type: object
        properties:
          source_path:
            type: string
          date_range:
            type: object
            properties:
              start_date:
                type: string
                format: date
              end_date:
                type: string
                format: date
    - name: "ingest.rss-feeds"
      description: "Process RSS feeds and articles (replaces Foresight m2 RSS logic)"
      input_schema:
        type: object
        properties:
          rss_urls:
            type: array
            items:
              type: string
              format: uri
          polling_interval:
            type: integer
            default: 3600
    - name: "ingest.normalize-content"
      description: "Unified content normalization regardless of source"
      input_schema:
        type: object
        properties:
          raw_content:
            type: object
          source_type:
            type: string
            enum: ["json", "rss", "api"]
  communication:
    protocol: "json-rpc-2.0"
    transport: "http"
    endpoints:
      - name: "primary"
        url: "http://content-ingestion-agent.signal-detection.svc.cluster.local:8090"
  scaling:
    min_replicas: 1
    max_replicas: 5
    target_cpu_utilization: 70