apiVersion: v1
kind: Namespace
metadata:
  name: signal-detection
  labels:
    app.kubernetes.io/name: signal-detection-platform
    app.kubernetes.io/part-of: foresight-modernization
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: signal-detection-config
  namespace: signal-detection
data:
  # Agent Communication
  protocol_version: "1.0"
  request_timeout: "30s"
  heartbeat_interval: "10s"
  
  # Processing Configuration
  batch_size: "50"
  confidence_threshold: "0.7"
  classification_threshold: "0.8"
  
  # Data Storage
  database_url: "postgresql://signal-detection:signals2024@postgres:5432/signal_detection"
  graph_enabled: "true"
  
  # Observability
  metrics_enabled: "true"
  log_level: "info"
---
apiVersion: v1
kind: Secret
metadata:
  name: signal-detection-secrets
  namespace: signal-detection
type: Opaque
data:
  database_password: c2lnbmFsczIwMjQ=  # signals2024
  api_key: ZGVtby1hcGkta2V5           # demo-api-key