apiVersion: apps/v1
kind: Deployment
metadata:
  name: pattern-detection-agent
  namespace: signal-detection
  labels:
    app.kubernetes.io/name: pattern-detection-agent
    app.kubernetes.io/component: detection
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: pattern-detection-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pattern-detection-agent
        app.kubernetes.io/component: detection
    spec:
      containers:
      - name: pattern-detection
        image: ghcr.io/simardeep1792/signal-detection-patterns:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8090
          name: agent-api
        - containerPort: 8091
          name: streaming
        env:
        - name: AGENT_TYPE
          value: "pattern-detection"
        - name: CONFIDENCE_THRESHOLD
          valueFrom:
            configMapKeyRef:
              name: signal-detection-config
              key: confidence_threshold
        - name: BATCH_SIZE
          valueFrom:
            configMapKeyRef:
              name: signal-detection-config
              key: batch_size
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: signal-detection-config
              key: log_level
        resources:
          requests:
            cpu: 400m
            memory: 768Mi
          limits:
            cpu: 2000m
            memory: 3Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - name: pattern-cache
          mountPath: /cache
        - name: analysis-workspace
          mountPath: /workspace
      volumes:
      - name: pattern-cache
        persistentVolumeClaim:
          claimName: signal-detection-patterns
      - name: analysis-workspace
        emptyDir:
          sizeLimit: 3Gi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: pattern-detection-agent
  namespace: signal-detection
spec:
  selector:
    app.kubernetes.io/name: pattern-detection-agent
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: agent-api
    port: 8090
    targetPort: 8090
  - name: streaming
    port: 8091
    targetPort: 8091
---
apiVersion: openagent.dev/v1
kind: Agent
metadata:
  name: pattern-detection-agent
  namespace: signal-detection
spec:
  type: pattern-detection
  version: "1.0.0"
  capabilities:
    - name: "detect.cluster-documents"
      description: "Document clustering (consolidates Foresight m1/m2 clustering)"
      input_schema:
        type: object
        properties:
          documents:
            type: array
            items:
              type: object
          clustering_method:
            type: string
            enum: ["hierarchical", "kmeans", "dbscan"]
            default: "hierarchical"
          similarity_threshold:
            type: number
            minimum: 0.0
            maximum: 1.0
            default: 0.7
    - name: "detect.similarity-analysis"
      description: "Document similarity and relationship detection"
      input_schema:
        type: object
        properties:
          query_document:
            type: object
          document_collection:
            type: array
            items:
              type: object
          max_results:
            type: integer
            default: 50
    - name: "detect.anomaly-detection"
      description: "Real-time anomaly and signal detection"
      input_schema:
        type: object
        properties:
          data_stream:
            type: array
            items:
              type: object
          baseline_window:
            type: string
            default: "7d"
          sensitivity:
            type: string
            enum: ["low", "medium", "high"]
            default: "medium"
    - name: "detect.trend-analysis"
      description: "Temporal pattern and trend identification"
      input_schema:
        type: object
        properties:
          time_series_data:
            type: array
            items:
              type: object
          time_window:
            type: string
            default: "24h"
          trend_threshold:
            type: number
            default: 0.05
  communication:
    protocol: "json-rpc-2.0"
    transport: "http+websocket"
    endpoints:
      - name: "primary"
        url: "http://pattern-detection-agent.signal-detection.svc.cluster.local:8090"
      - name: "streaming"
        url: "ws://pattern-detection-agent.signal-detection.svc.cluster.local:8091"
  scaling:
    min_replicas: 1
    max_replicas: 4
    target_cpu_utilization: 80