apiVersion: apps/v1
kind: Deployment
metadata:
  name: signal-processing-agent
  namespace: signal-detection
  labels:
    app.kubernetes.io/name: signal-processing-agent
    app.kubernetes.io/component: processing
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: signal-processing-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: signal-processing-agent
        app.kubernetes.io/component: processing
    spec:
      containers:
      - name: signal-processing
        image: ghcr.io/simardeep1792/signal-detection-processing:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8090
          name: agent-api
        env:
        - name: AGENT_TYPE
          value: "signal-processing"
        - name: CONFIDENCE_THRESHOLD
          valueFrom:
            configMapKeyRef:
              name: signal-detection-config
              key: confidence_threshold
        - name: BATCH_SIZE
          valueFrom:
            configMapKeyRef:
              name: signal-detection-config
              key: batch_size
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: signal-detection-config
              key: log_level
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - name: models-cache
          mountPath: /models
        - name: temp-processing
          mountPath: /tmp
      volumes:
      - name: models-cache
        persistentVolumeClaim:
          claimName: signal-detection-models
      - name: temp-processing
        emptyDir:
          sizeLimit: 2Gi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: signal-processing-agent
  namespace: signal-detection
spec:
  selector:
    app.kubernetes.io/name: signal-processing-agent
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: agent-api
    port: 8090
    targetPort: 8090
---
apiVersion: openagent.dev/v1
kind: Agent
metadata:
  name: signal-processing-agent
  namespace: signal-detection
spec:
  type: signal-processing
  version: "1.0.0"
  capabilities:
    - name: "process.nlp-analysis"
      description: "Modern NLP processing (replaces Foresight m1 preprocess + m2 language-identifier)"
      input_schema:
        type: object
        properties:
          documents:
            type: array
            items:
              type: object
          extract_entities:
            type: boolean
            default: true
          detect_language:
            type: boolean
            default: true
    - name: "process.entity-extraction"
      description: "Health entity extraction using transformer models"
      input_schema:
        type: object
        properties:
          text:
            type: string
          entity_types:
            type: array
            items:
              type: string
              enum: ["person", "organization", "location", "disease", "symptom"]
    - name: "process.semantic-enrichment"
      description: "Add semantic context and metadata"
      input_schema:
        type: object
        properties:
          documents:
            type: array
            items:
              type: object
          enrichment_level:
            type: string
            enum: ["basic", "standard", "comprehensive"]
            default: "standard"
  communication:
    protocol: "json-rpc-2.0"
    transport: "http"
    endpoints:
      - name: "primary"
        url: "http://signal-processing-agent.signal-detection.svc.cluster.local:8090"
  scaling:
    min_replicas: 2
    max_replicas: 8
    target_cpu_utilization: 75