apiVersion: v1
kind: Namespace
metadata:
  name: foresight-agents
  labels:
    app.kubernetes.io/name: foresight-platform
    app.kubernetes.io/component: agent-namespace
    app.kubernetes.io/part-of: open-agent-platform
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
  annotations:
    description: "Public Health Agency Foresight platform reimagined as agent-based system"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: foresight-config
  namespace: foresight-agents
  labels:
    app.kubernetes.io/name: foresight-platform
    app.kubernetes.io/component: configuration
data:
  # A2A Protocol Configuration
  protocol_version: "1.0"
  communication_mode: "json-rpc-2.0"
  max_concurrent_requests: "50"
  request_timeout: "30s"
  heartbeat_interval: "10s"
  
  # Foresight-specific Configuration
  surveillance_pipelines: "64"
  participating_jurisdictions: "13"
  data_retention_days: "365"
  alert_threshold_high: "0.8"
  alert_threshold_medium: "0.6"
  
  # Agent Registry
  registry_endpoint: "http://open-agent-platform-registry.oapf-dev.svc.cluster.local:80"
  
  # Observability
  metrics_enabled: "true"
  tracing_enabled: "true"
  log_level: "info"
---
apiVersion: v1
kind: Secret
metadata:
  name: foresight-secrets
  namespace: foresight-agents
  labels:
    app.kubernetes.io/name: foresight-platform
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Base64 encoded values (demo credentials)
  social_media_api_key: ZGVtby1hcGkta2V5LWZvci1zb2NpYWwtbWVkaWE=
  news_api_key: ZGVtby1hcGkta2V5LWZvci1uZXdz
  nlp_service_token: ZGVtby1ubHAtc2VydmljZS10b2tlbg==
  database_password: ZGVtby1kYXRhYmFzZS1wYXNzd29yZA==