apiVersion: v1
kind: Namespace
metadata:
  name: foresight-agents
  labels:
    app.kubernetes.io/name: foresight-platform
    app.kubernetes.io/component: agent-namespace
    app.kubernetes.io/part-of: foresight-signal-detection
    foresight.ca/platform: enabled
  annotations:
    description: "Agent-based Foresight signal detection platform"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: foresight-config
  namespace: foresight-agents
  labels:
    app.kubernetes.io/name: foresight-platform
    app.kubernetes.io/component: configuration
data:
  # Agent-to-Agent Protocol Configuration
  protocol_version: "1.0"
  communication_mode: "json-rpc-2.0"
  max_concurrent_requests: "100"
  request_timeout: "60s"
  heartbeat_interval: "10s"
  
  # Foresight Pipeline Configuration
  batch_size: "50"
  clustering_threshold: "0.8"
  similarity_threshold: "0.7"
  enrichment_batch_size: "25"
  
  # Data Sources (from original Foresight)
  json_source_path: "/data/sources"
  output_path: "/data/processed"
  neo4j_endpoint: "neo4j://foresight-neo4j:7687"
  
  # Agent Registry
  registry_endpoint: "http://open-agent-platform-registry.oapf-dev.svc.cluster.local:80"
  
  # Observability
  metrics_enabled: "true"
  tracing_enabled: "true"
  log_level: "info"
---
apiVersion: v1
kind: Secret
metadata:
  name: foresight-secrets
  namespace: foresight-agents
  labels:
    app.kubernetes.io/name: foresight-platform
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Base64 encoded values
  neo4j_user: Zm9yZXNpZ2h0
  neo4j_password: c2lnbmFsX2RldGVjdGlvbl8yMDI0
  api_key: ZGVtby1hcGkta2V5LWZvcmVzaWdodA==