apiVersion: v1
kind: Service
metadata:
  name: a2a-registry
  labels:
    app.kubernetes.io/name: a2a-registry
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: a2a-platform
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: websocket
    port: 8080
    targetPort: websocket
    protocol: TCP
  selector:
    app.kubernetes.io/name: a2a-registry
    app.kubernetes.io/component: registry
---
apiVersion: v1
kind: Service
metadata:
  name: a2a-registry-headless
  labels:
    app.kubernetes.io/name: a2a-registry
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: a2a-platform
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: a2a-registry
    app.kubernetes.io/component: registry